# Generated by Django 3.2.8 on 2021-10-22 11:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='show_to_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
