# Generated by Django 3.2.8 on 2021-10-16 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_auto_20211016_2019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='followers',
            options={'verbose_name_plural': 'Followers'},
        ),
        migrations.AlterField(
            model_name='followers',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
